# Generated by Django 3.2.14 on 2024-01-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='anser',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='anser',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='name',
            field=models.CharField(max_length=100, verbose_name='題庫類別'),
        ),
    ]
