# Generated by Django 3.2.14 on 2024-01-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_auto_20240106_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='anser',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='anser',
        ),
        migrations.AddField(
            model_name='question',
            name='question_details',
            field=models.TextField(blank=True),
        ),
    ]
